### ISSUE TITLE
LetoDBF

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [ronpinkas/xharbour#1]
Could you please insert Elch's fork of LetoDBF into the contribs?
I didn´t find anybody who could compile it with xharbour...
[https://github.com/elchs/LetoDBf](https://github.com/elchs/LetoDBf)

Another issue, this version of xharbour is v1.2.3? Which is?

**Comment by ronpinkas** [comment]
Sorry, this is not the place for such issues. Please ask the respective developer for such support. or try to get assistance at:

https://groups.google.com/g/comp.lang.xharbour
