### ISSUE TITLE
doesn't build on osx

### ISSUE THREAD

**Issue by dataf3l** [ronpinkas/xharbour#15]
➜  xharbour git:(main) ./make_macosx.sh
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C include
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C source
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C common
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../expropt1.c -oexpropt1.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../expropt2.c -oexpropt2.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbfsapi.c -ohbfsapi.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbfopen.c -ohbfopen.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbgete.c -ohbgete.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbwince.c -ohbwince.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbhash.c -ohbhash.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbstr.c -ohbstr.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbprintf.c -ohbprintf.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbdate.c -ohbdate.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbtrace.c -ohbtrace.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbver.c -ohbver.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbarch.c -ohbarch.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../reserved.c -oreserved.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../hbmem.c -ohbmem.o
libtool -static  -o libcommon.a expropt1.o expropt2.o hbfsapi.o hbfopen.o hbgete.o hbwince.o hbhash.o hbstr.o hbprintf.o hbdate.o hbtrace.o hbver.o hbarch.o reserved.o hbmem.o || ( rm -f libcommon.a && false )
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C pp
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../ppgen.c -oppgen.o
gcc -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -o ppgen ppgen.o   -L../../../../source/common/darwin/gcc      -lcommon -lm    -lcommon -lm
./ppgen ../../../../include/hbstdgen.ch -opptable.c -q -c../../../../ChangeLog -v../../../../include/hbverbld.h -x../../../../source/compiler/ppword.c
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c pptable.c -opptable.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../ppcore.c -oppcore.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../pplib.c -opplib.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../pplib2.c -opplib2.o
gcc -I. -I../../include -I../../../../include -no-cpp-precomp -fno-common -Wall -W -DHB_NO_DV_MEMCPY -DHB_OS_DARWIN -c ../../pplib3.c -opplib3.o
libtool -static  -o libpp.a pptable.o ppcore.o pplib.o pplib2.o pplib3.o || ( rm -f libpp.a && false )
rm ppgen.o
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C compiler
bison -d  -oharboury.c ../../harbour.sly
../../harbour.sly:1.9-18: syntax error, unexpected identifier, expecting string
make[3]: *** [harboury.c] Error 1
make[2]: *** [descend] Error 2
make[1]: *** [compiler] Error 2
make: *** [source] Error 2

**Comment by ronpinkas** [comment]
Hi Felipe, use make_drw.sh instead. We need to delete make_macosx.sh.

**Comment by ronpinkas** [comment]
Now make_macosx.sh is using make_drw.sh.

**Comment by dataf3l** [comment]
Thank you all for your concerted efforts.
I am using an M1 machine, unfortunately, using this commit:

45b04a722f8218d83829f81d56e21ea4db13934e

```
./make_macosx.sh
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C include
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C source
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C common
make[3]: `libcommon.a' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C pp
make[3]: `libpp.a' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C compiler
bison -d  -oharboury.c ../../harbour.sly
../../harbour.sly:1.9-18: syntax error, unexpected identifier, expecting string
make[3]: *** [harboury.c] Error 1
make[2]: *** [descend] Error 2
make[1]: *** [compiler] Error 2
make: *** [source] Error 2
➜  xharbour git:(main)
```

I have no clue on what to do next, to be honest.

**Comment by ronpinkas** [comment]
You need to follow the install instructions n make_drw.sh specifically you
need new (current) version of bison.
