### ISSUE TITLE
xHarbour Rev. 10269

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [ronpinkas/xharbour#2]
Hi,

Is this source equivalent to xHarbour Rev. 10269 binaries?
Can I use this xharbour with BCC58? Do you know why they don´t distribute xharbour+BCC58 anymore?

Anderson

**Comment by ronpinkas** [comment]
Yes, Binary builds are built directly from these sources at time of build. You may donate such a build if you own BCC 5.8.
