### ISSUE TITLE
improvements or gains in productivity in rddsql

### ISSUE THREAD

**Issue by ivanilmarcelino** [ronpinkas/xharbour#24]
Adjust in  sqlconnection.prg
METHOD Execute(cCommand, lErrMsg, nLogMode, cType, lNeverLog) CLASS SR_CONNECTION
...
Line 727
         IF ::nAutoCommit > 0 .AND. Upper(SubStr(ltrim(cCommand), 1, 6)) $ "UPDATE,INSERT,DELETE"
            IF (++::nIteractions) >= ::nAutoCommit .AND. ::nTransacCount == 0
               ::Commit()
            ENDIF
*Begin Add
        ELSE
                ::IniFields(.F.,,,,, /*cRecnoName*/,/*cDeletedName*/)
*End Add
         ENDIF
...

Add Method in sqlconnection.prg
*Begin
METHOD GetHash(hLine, lTranslate, aFields) CLASS SR_CONNECTION

   LOCAL lResults := HB_ISHASH(hLine)
   LOCAL i
   LOCAL nRet := ::FetchRaw(lTranslate, aFields)

   IF nRet == SQL_SUCCESS .AND. lResults
      FOR i := 1 TO ::nFields
         hline[lower(::afields[i,1])] := ::FieldGet(i, ::aFields, lTranslate)
      NEXT i
   ENDIF

RETURN nRet
*End

**Comment by eduardomotta-emottasistemas** [comment]
Ideally, you should explain the reason for the change and make a pull request with the fix to be analyzed

**Comment by ronpinkas** [comment]
Please post a pull request.
