### ISSUE TITLE
Unresolved external '___get_std_stream' referenced from COMMON.LIB|hbtrace

### ISSUE THREAD

**Issue by GHExplorer** [ronpinkas/xharbour#25]
Hi,

I'm having problems compiling the very simplest of code in the \xhb\tests\ folder.

I'm using bld.bat, after first assigning the environmental variables

SET HB_ARCHITECTURE=w32
SET HB_COMPILER=bcc32
set HB_INSTALL=c:\xhb
set HB_BIN_INSTALL=c:\xhb\bin
SET HB_INC_INSTALL=c:\xhb\include;c:\bcc582\include
SET HB_LIB_INSTALL=c:\xhb\lib;c:\bcc582\lib

(There's all sorts of errors, if these aren't assigned first).

I searched through libraries to figure out where the get_std_stream module is defined.  There are references in the \xhb\lib folder, but the actual definition doesn't seem to be in any of these libraries.  (I generated a list file for each library, and searched through the list files).

**Comment by ronpinkas** [comment]
You should use bld_b32.bat if you use bcc

**Comment by GHExplorer** [comment]
Hi,

bld_b32.bat just consists of a call to bld.bat

@echo off
rem
rem $Id$
rem

rem ---------------------------------------------------------------
rem This is a generic template file, if it doesn't fit your own needs 
rem please DON'T MODIFY IT.
rem
rem Instead, make a local copy and modify that one, or make a call to 
rem this batch file from your customized one. [vszakats]
rem ---------------------------------------------------------------

set HB_ARCHITECTURE=w32
set HB_COMPILER=bcc32

call bld.bat %1 %2 %3 %4 %5 %6 %7 %8 %9

**Comment by GHExplorer** [comment]
Hi Ron,

Continued from the xbscript thread,

We got further using bcc7.70, there's no errors.  But it doesn't complete the linking.

Using \xhb\tests\ac_test.prg as an example,

Whether bld.bat or bld_b32.bat is used, it goes as far as generating ac_test.obj.

The final bcc32 command is

bcc32  -O2 -d  -Ic:\xhb\include;c:\BCC7\include -Lc:\xhb\lib ac_test.c common.lib debug.lib vm.lib rtl.lib zlib.lib pcrepos.lib gtwin.lib lang.lib rdd.lib macro.lib pp.lib dbffpt.lib dbfntx.lib dbfcdx.lib bmdbfcdx.lib redbfcdx.lib hsx.lib hbsix.lib ct.lib tip.lib

, which I think should call the linker, but maybe it doesn't.  The .c and .obj are generated, but not the final executable.

You mentioned in the XBScript thread, to try msvc.  I will do that, thanks.

**Comment by ronpinkas** [comment]
Sorry meant to say MS VC.

**Comment by GHExplorer** [comment]
I understood, thanks.  

The msvc command line tools are in a different place from the link on the xHarbour binaries page.  The build tools, rather than the visual studio full package, is at

https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022

**Comment by ronpinkas** [comment]
Installer allows you to select components IIRC.

**Comment by ronpinkas** [comment]
bld_bc.bat and bld_vc.bat do NOT just call bld.bat they first set respective compiler including auto detection. Also xbScsript is built as part of the normal build of xHarbour itself, using make_bc.bat make_vc.ba make_pc.bat etc.. depending on the desired compiler.
