### ISSUE TITLE
Compile error BCC58+BISON

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [ronpinkas/xharbour#4]
[make_b32.log](https://github.com/ronpinkas/xharbour/files/11712442/make_b32.log)
It´s not compiling...
I used "make_bc all" and I got this:

> source\compiler\harbour.c:
>         1 arquivo(s) copiado(s).
> obj\b32\comptool.c:
> Warning W8056 obj\b32\comptool.c 631: Integer arithmetic overflow in function hb_verCvsID
> obj\b32\harboury.c:
> Error E2141 harboury.c 4545: Declaration syntax error in function hb_comp_yyparse
> *** 1 errors in Compile ***
> 
> ** error 1 ** deleting obj\b32\harboury.obj

I have Borland C at \BCC58 and Bison at \GnuWin32, I think it should be ok.

**make_bc.bat** is not working!

This xharbour from source I saved in **c:\xhbgit** folder.

My batch env:

```
SET BISON_DIR=\GnuWin32\Bin
SET CC_DIR=\BCC58

SET PATH=C:\XHBGIT\BIN;C:\BCC58\BIN;C:\GnuWin32\Bin;C:\WINDOWS
SET HB_DIR=C:\XHBGIT
SET HB_PATH=C:\XHBGIT
SET INCLUDE=C:\XHBGIT\INCLUDE;C:\BCC58\INCLUDE
SET LIB=C:\XHBGIT\LIB;C:\BCC58\LIB
```

**Comment by ronpinkas** [comment]
Fixed.
