### ISSUE TITLE
compiler xbuild

### ISSUE THREAD

**Issue by sygecom** [ronpinkas/xharbour#68]
Please,
Could anyone describe how I compile the xbuild project ( \xharbour\xHarbourBuilder\xHarbour-xBuild ) ?

I have already managed to compile xharbour with Mingw64 (64 bits)

**Comment by sygecom** [comment]
?

**Comment by ronpinkas** [comment]
Please post your questions to news://comp.lang.xharbour

**Comment by sygecom** [comment]
It is blocked from new messages
