### ISSUE TITLE
building xharbour with Pelles ISO C Compiler, Version 12.00.1 

### ISSUE THREAD

**Issue by omm** [ronpinkas/xharbour#72]
Hi,

i'm got an error while building xharbour

```
For your convenience xHarbour's bin directory was added to your PATH.
Searching for Pelles C...
For your convenience pocc's bin directory was added to your PATH
Defaulting HB_ARCH to w32.
Creating System Files (ST) ...
POMAKE: fatal error: Don't know how to make 'utils\xbscript\xbscript.prg'.

```
What version of PellesC should i use? Thanks

**Comment by ronpinkas** [comment]
The problem is not the compiler - you did not use the correct git command so you do not have xbscript module. Use this command: 

   git clone --recurse-submodules https://github.com/xHarbour-org/xharbour.git

Then build same as you did.
