### ISSUE TITLE
gpf error - windows server 2012 R2

### ISSUE THREAD

**Issue by eduardomotta-emottasistemas** [ronpinkas/xharbour#8]
This code is generating GPF before closing the program.
On windows 10 it works without errors, but when running on a windows server 2012 R2 it is giving the error.
The program was compiled with xHarbour on 08/24/2023.
To simulate the error, just compile the program below and run it on a Windows Server 2012 R2 machine.

![xharbour gpf](https://github.com/ronpinkas/xharbour/assets/64843365/97ff538c-f99a-47a8-923d-bdd7c4b974ca)

Function Test_Sql()
? Version() // xHarbour 1.2.3 Intl. (SimpLex) (Build 20230823)
? HB_PCodeVer() // PCode Version: 10
? HB_Compiler() // Microsoft Visual C++ 19.37.32822 (32-bit)
? HB_BuildDate() // Aug 24 2023 16:35:39
Return

**Comment by ronpinkas** [comment]
Did this just started after recent commit?

**Comment by eduardomotta-emottasistemas** [comment]
Ron, I'm not sure if it was just the last commit. Today I pulled and
compiled and when I put it on a machine with Windows server 2012 the error
occurred. On my development machine, which is W10, everything works fine.

Em qui, 24 de ago de 2023 17:34, Ron[ny] Pinkas ***@***.***>
escreveu:

> Did this just started after recent commit?
>
> On Thu, Aug 24, 2023, 15:13 eduardomotta-emottasistemas <

**Comment by ronpinkas** [comment]
I suspect recent modification. I will correct soon and have you test.

**Comment by ronpinkas** [comment]
Try after: 2023-08-24 20:45 UTC-0500 Ron Pinkas <ronpinkas/AT/gmail/com>

**Comment by eduardomotta-emottasistemas** [comment]
Ron, it worked! 

You can close the issue

thanks
